/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author epidu
 */
public class Inicio_Sistema extends javax.swing.JFrame {
           public static int tamanoIntro;
           public static int tamanoCreditos;
           public static int tamanoInicio;
           public static int tamanoCierre;
           public static int tamanoPlot;

           /**
            * Creates new form Inicio_Sistema
            */
           public Inicio_Sistema() {
                      initComponents();
                      this.setLocationRelativeTo(null);
                      this.setResizable(false);
           }

           /**
            * This method is called from within the constructor to initialize
            * the form. WARNING: Do NOT modify this code. The content of this
            * method is always regenerated by the Form Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jPanel1 = new javax.swing.JPanel();
                      jLabel1 = new javax.swing.JLabel();
                      No = new javax.swing.JButton();
                      si = new javax.swing.JButton();

                      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                      jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                      getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

                      jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
                      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("Desea tener espacios de disco duro infiinito");
                      getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

                      No.setText("No");
                      No.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            NoActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 80, -1));

                      si.setText("Si");
                      si.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            siActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, -1));

                      pack();
           }// </editor-fold>//GEN-END:initComponents

           private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
                      // TODO add your handling code here:
                      tamanoIntro = 999999999;
                      tamanoCreditos = 999999999;
                      tamanoInicio = 999999999;
                      tamanoCierre = 999999999;
                      tamanoPlot = 999999999;
                      casaRodaje inicial = new casaRodaje();
                      inicial.setVisible(true);
                      this.dispose();
                      
           }//GEN-LAST:event_siActionPerformed

           private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
                      // TODO add your handling code here:
                      tamanoIntro = 30;
                      tamanoCreditos = 25;
                      tamanoInicio = 50;
                      tamanoCierre = 55;
                      tamanoPlot = 40;
                      casaRodaje inicial = new casaRodaje();
                      inicial.setVisible(true);
                      this.dispose();
           }//GEN-LAST:event_NoActionPerformed

           /**
            * @param args the command line arguments
            */
           public static void main(String args[]) {
                      /* Set the Nimbus look and feel */
                      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                       */
                      try {
                                 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                            if ("Nimbus".equals(info.getName())) {
                                                       javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                       break;
                                            }
                                 }
                      } catch (ClassNotFoundException ex) {
                                 java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (InstantiationException ex) {
                                 java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (IllegalAccessException ex) {
                                 java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                                 java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      }
                      //</editor-fold>

                      /* Create and display the form */
                      java.awt.EventQueue.invokeLater(new Runnable() {
                                 public void run() {
                                            new Inicio_Sistema().setVisible(true);
                                 }
                      });
           }

           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton No;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JPanel jPanel1;
           private javax.swing.JButton si;
           // End of variables declaration//GEN-END:variables
}
