/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author epidu
 */
public class Inicio_Sistema extends javax.swing.JFrame {
           public static int tamanoIntro;
           public static int tamanoCreditos;
           public static int tamanoInicio;
           public static int tamanoCierre;
           public static int tamanoPlot;
           public static int dias_entrega;
           public static int periodo_temporadas;
           public static int Horas;
           public static int Cedula;
           public static int cedula;
           public static int cedula_Intro;
           public static int cedula_Inicio;
           public static int cedula_Cierre;
           public static int cedula_Creditos;
           public static int cedula_Plot;
           public static int cedula_PM_contador;
           public static int cedula_PM_intervalos;
           public static int inicio_productores;
           public static int cierre_productores;
           public static int intro_productores;
           public static int creditos_productores;
           public static int plot_productores;
           public static int ensambladores;
           
           
           /**
            * Creates new form Inicio_Sistema
            */
           public Inicio_Sistema() {
                      initComponents();
                      this.setLocationRelativeTo(null);
                      this.setResizable(false);
           }
           
           public void cedula(int Cedula){
                      if( Cedula>=0  && Cedula < 3){
                                 cedula_Intro = 1;
                                 cedula_Inicio = 2;
                                 cedula_Cierre = 4;
                                 cedula_Creditos = 4;
                                 
                      }else if( Cedula>=3  && Cedula < 6){
                                 cedula_Intro = 2;
                                 cedula_Inicio = 3;
                                 cedula_Cierre = 2;
                                 cedula_Creditos = 2;
                                 
                      }else{
                                 cedula_Intro = 3;
                                 cedula_Inicio = 4;
                                 cedula_Cierre = 3;
                                 cedula_Creditos = 3;
                                 
                      }
                      if(Cedula>=0  && Cedula < 5){
                                 cedula_Plot = 2;
                      }else{
                                 cedula_Plot = 3;
                      }
                      
                      cedula_PM_contador = 1 + Cedula;
                      cedula_PM_intervalos = 15 + Cedula;
                      
           }
           
                           
           

           /**
            * This method is called from within the constructor to initialize
            * the form. WARNING: Do NOT modify this code. The content of this
            * method is always regenerated by the Form Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jScrollPane1 = new javax.swing.JScrollPane();
                      jTextArea1 = new javax.swing.JTextArea();
                      jPanel1 = new javax.swing.JPanel();
                      jLabel1 = new javax.swing.JLabel();
                      No = new javax.swing.JButton();
                      si = new javax.swing.JButton();
                      TextField_Dias_de_entrega = new javax.swing.JTextField();
                      TextField_Periodo_de_temporadas = new javax.swing.JTextField();
                      jLabel2 = new javax.swing.JLabel();
                      jLabel3 = new javax.swing.JLabel();

                      jTextArea1.setColumns(20);
                      jTextArea1.setRows(5);
                      jScrollPane1.setViewportView(jTextArea1);

                      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                      jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                      getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

                      jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
                      jLabel1.setForeground(new java.awt.Color(0, 0, 0));
                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("Desea tener espacios de disco duro infiinito");
                      getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, -1));

                      No.setText("No");
                      No.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            NoActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 80, -1));

                      si.setText("Si");
                      si.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            siActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, -1));

                      TextField_Dias_de_entrega.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            TextField_Dias_de_entregaActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(TextField_Dias_de_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, -1));

                      TextField_Periodo_de_temporadas.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            TextField_Periodo_de_temporadasActionPerformed(evt);
                                 }
                      });
                      getContentPane().add(TextField_Periodo_de_temporadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 80, -1));

                      jLabel2.setText("Periodo de entrega de temporadas");
                      getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

                      jLabel3.setText("Dias para entregar el proyecto");
                      getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                      pack();
           }// </editor-fold>//GEN-END:initComponents

           private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
                      // TODO add your handling code here:
                      try{
                                 if(Integer.parseInt(TextField_Dias_de_entrega.getText()) > 0 && Integer.parseInt(TextField_Periodo_de_temporadas.getText()) > 0){
                                            
                                            tamanoIntro = 999999999;
                                            tamanoCreditos = 999999999;
                                            tamanoInicio = 999999999;
                                            tamanoCierre = 999999999;
                                            tamanoPlot = 999999999;
                                            Horas = 1000;
                                            Cedula = 3;
                                            cedula(Cedula);
                                            inicio_productores=0;
                                            cierre_productores=0;
                                            intro_productores=0;
                                            creditos_productores=0;
                                            plot_productores=0;
                                            ensambladores=0;
                                            dias_entrega = Integer.parseInt(TextField_Dias_de_entrega.getText()); 
                                            periodo_temporadas =Integer.parseInt(TextField_Periodo_de_temporadas.getText());
                                            casaRodaje inicial = new casaRodaje();
                                            inicial.setVisible(true);
                                            this.dispose();
                                 }            
                      }catch(NumberFormatException e){
                                 JOptionPane.showMessageDialog(null,"Un campo se encuentra incompleto");
                      }
                      
                      
           }//GEN-LAST:event_siActionPerformed

           private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed

                      try{
                                 if(Integer.parseInt(TextField_Periodo_de_temporadas.getText()) > 0 && Integer.parseInt(TextField_Dias_de_entrega.getText()) > 0){
                                            tamanoIntro = 30;
                                            tamanoCreditos = 25;
                                            tamanoInicio = 50;
                                            tamanoCierre = 55;
                                            tamanoPlot = 40;
                                            Horas = 1000;
                                            Cedula = 3;
                                            cedula(Cedula);
                                            inicio_productores=0;
                                            cierre_productores=0;
                                            intro_productores=0;
                                            creditos_productores=0;
                                            plot_productores=0;
                                            ensambladores=0;
                                            dias_entrega = Integer.parseInt(TextField_Dias_de_entrega.getText()); 
                                            periodo_temporadas =Integer.parseInt(TextField_Periodo_de_temporadas.getText());
                                            casaRodaje inicial = new casaRodaje();
                                            inicial.setVisible(true);
                                            this.dispose();
                                 }
                      }catch(NumberFormatException e){
                                 JOptionPane.showMessageDialog(null,"Un campo se encuentra incompleto");
                      }
           }//GEN-LAST:event_NoActionPerformed

           private void TextField_Dias_de_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Dias_de_entregaActionPerformed
                      // TODO add your handling code here:
                      try {
                                 dias_entrega = Integer.parseInt(TextField_Dias_de_entrega.getText()); 
                      } catch (NumberFormatException ex) {
                                 JOptionPane.showMessageDialog(null,"Ingrese un valor entero valido");
                      }
           }//GEN-LAST:event_TextField_Dias_de_entregaActionPerformed

           private void TextField_Periodo_de_temporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Periodo_de_temporadasActionPerformed
                      // TODO add your handling code here:
                      try {
                                 periodo_temporadas =Integer.parseInt(TextField_Periodo_de_temporadas.getText());
                      } catch (NumberFormatException ex) {
                                 JOptionPane.showMessageDialog(null,"Ingrese un valor entero valido");
                      }
           }//GEN-LAST:event_TextField_Periodo_de_temporadasActionPerformed

           /**
            * @param args the command line arguments
            */
           public static void main(String args[]) {
                      /* Set the Nimbus look and feel */
                      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                       */
                      try {
                                 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                            if ("Nimbus".equals(info.getName())) {
                                                       javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                       break;
                                            }
                                 }
                      } catch (ClassNotFoundException ex) {
                                 java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (InstantiationException ex) {
                                 java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (IllegalAccessException ex) {
                                 java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                                 java.util.logging.Logger.getLogger(Inicio_Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      }
                      //</editor-fold>

                      /* Create and display the form */
                      java.awt.EventQueue.invokeLater(new Runnable() {
                                 public void run() {
                                            new Inicio_Sistema().setVisible(true);
                                 }
                      });
           }

           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton No;
           private javax.swing.JTextField TextField_Dias_de_entrega;
           private javax.swing.JTextField TextField_Periodo_de_temporadas;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel2;
           private javax.swing.JLabel jLabel3;
           private javax.swing.JPanel jPanel1;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JTextArea jTextArea1;
           private javax.swing.JButton si;
           // End of variables declaration//GEN-END:variables
}
