/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author epidu
 */
public class Reporte extends javax.swing.JFrame {

           /**
            * Creates new form Reporte
            */
           public Reporte() {
                      initComponents();
           }

           /**
            * This method is called from within the constructor to initialize
            * the form. WARNING: Do NOT modify this code. The content of this
            * method is always regenerated by the Form Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jPanel1 = new javax.swing.JPanel();
                      jLabel1 = new javax.swing.JLabel();
                      jLabel3 = new javax.swing.JLabel();
                      jLabel4 = new javax.swing.JLabel();
                      jLabel6 = new javax.swing.JLabel();
                      jLabel7 = new javax.swing.JLabel();
                      jLabel12 = new javax.swing.JLabel();
                      jLabel13 = new javax.swing.JLabel();
                      jLabel14 = new javax.swing.JLabel();
                      jLabel15 = new javax.swing.JLabel();
                      jLabel16 = new javax.swing.JLabel();
                      jLabel17 = new javax.swing.JLabel();
                      jLabel18 = new javax.swing.JLabel();
                      jLabel19 = new javax.swing.JLabel();
                      jLabel5 = new javax.swing.JLabel();
                      jLabel20 = new javax.swing.JLabel();
                      jLabel21 = new javax.swing.JLabel();
                      jLabel22 = new javax.swing.JLabel();
                      jLabel23 = new javax.swing.JLabel();
                      jLabel24 = new javax.swing.JLabel();
                      jLabel25 = new javax.swing.JLabel();
                      jLabel26 = new javax.swing.JLabel();
                      jLabel27 = new javax.swing.JLabel();
                      jLabel28 = new javax.swing.JLabel();
                      jLabel29 = new javax.swing.JLabel();
                      jLabel30 = new javax.swing.JLabel();
                      jLabel31 = new javax.swing.JLabel();
                      jLabel32 = new javax.swing.JLabel();
                      jLabel33 = new javax.swing.JLabel();
                      jLabel34 = new javax.swing.JLabel();
                      jLabel35 = new javax.swing.JLabel();
                      jLabel36 = new javax.swing.JLabel();
                      jLabel37 = new javax.swing.JLabel();
                      jLabel38 = new javax.swing.JLabel();
                      jLabel39 = new javax.swing.JLabel();
                      jLabel40 = new javax.swing.JLabel();
                      jLabel41 = new javax.swing.JLabel();
                      jLabel42 = new javax.swing.JLabel();
                      jLabel43 = new javax.swing.JLabel();
                      jLabel44 = new javax.swing.JLabel();
                      jLabel45 = new javax.swing.JLabel();
                      jLabel46 = new javax.swing.JLabel();
                      jLabel47 = new javax.swing.JLabel();
                      jLabel48 = new javax.swing.JLabel();
                      jLabel49 = new javax.swing.JLabel();
                      jLabel50 = new javax.swing.JLabel();
                      jLabel51 = new javax.swing.JLabel();
                      jLabel52 = new javax.swing.JLabel();
                      jLabel53 = new javax.swing.JLabel();
                      jLabel54 = new javax.swing.JLabel();
                      jLabel55 = new javax.swing.JLabel();
                      jLabel56 = new javax.swing.JLabel();
                      jLabel57 = new javax.swing.JLabel();
                      jLabel58 = new javax.swing.JLabel();
                      jLabel59 = new javax.swing.JLabel();
                      jLabel60 = new javax.swing.JLabel();
                      jLabel61 = new javax.swing.JLabel();
                      jLabel62 = new javax.swing.JLabel();
                      jLabel63 = new javax.swing.JLabel();
                      jLabel64 = new javax.swing.JLabel();
                      jLabel65 = new javax.swing.JLabel();
                      jLabel66 = new javax.swing.JLabel();
                      jLabel67 = new javax.swing.JLabel();
                      jLabel68 = new javax.swing.JLabel();
                      jLabel69 = new javax.swing.JLabel();
                      jLabel70 = new javax.swing.JLabel();
                      jLabel71 = new javax.swing.JLabel();
                      jLabel72 = new javax.swing.JLabel();
                      jLabel73 = new javax.swing.JLabel();
                      jLabel74 = new javax.swing.JLabel();
                      jLabel75 = new javax.swing.JLabel();
                      jLabel76 = new javax.swing.JLabel();
                      jLabel77 = new javax.swing.JLabel();
                      jLabel78 = new javax.swing.JLabel();
                      jLabel79 = new javax.swing.JLabel();
                      jLabel80 = new javax.swing.JLabel();
                      jLabel81 = new javax.swing.JLabel();
                      jLabel82 = new javax.swing.JLabel();
                      jLabel83 = new javax.swing.JLabel();
                      jLabel84 = new javax.swing.JLabel();
                      jLabel85 = new javax.swing.JLabel();

                      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                      jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                      getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("Velma");
                      getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 110, -1));

                      jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel3.setText("GOT");
                      getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, -1));

                      jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel4.setText("Project Manager:");
                      getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 140, -1));

                      jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel6.setText("Ensambladores");
                      getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

                      jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel7.setText("GOT");
                      getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 60, -1));

                      jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel12.setText("Intro");
                      getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, -1));

                      jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel13.setText("Inicio");
                      getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

                      jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel14.setText("Cierre");
                      getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

                      jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel15.setText("Plot Twist");
                      getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, -1));

                      jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel16.setText("GOT");
                      getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 60, -1));

                      jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel17.setText("GOT");
                      getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 60, -1));

                      jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel18.setText("GOT");
                      getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 60, -1));

                      jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel19.setText("GOT");
                      getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 60, -1));

                      jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel5.setText("Productores:");
                      getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, -1));

                      jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel20.setText("Ensambladores");
                      getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, -1));

                      jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel21.setText("GOT");
                      getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 60, -1));

                      jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel22.setText("Intro");
                      getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, -1));

                      jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel23.setText("Inicio");
                      getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, -1));

                      jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel24.setText("Cierre");
                      getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 110, -1));

                      jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel25.setText("Plot Twist");
                      getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, -1));

                      jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel26.setText("GOT");
                      getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 60, -1));

                      jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel27.setText("GOT");
                      getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 60, -1));

                      jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel28.setText("GOT");
                      getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 60, -1));

                      jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel29.setText("GOT");
                      getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, -1));

                      jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel30.setText("Memoria Disponible:");
                      getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 150, -1));

                      jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel31.setText("Salario");
                      getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, -1));

                      jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel32.setText("Faltas");
                      getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, -1));

                      jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel33.setText("GOT");
                      getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 60, -1));

                      jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel34.setText("GOT");
                      getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 60, -1));

                      jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel35.setText("Facturacion:");
                      getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 110, -1));

                      jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel36.setText("Gastos");
                      getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 110, -1));

                      jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel37.setText("Ganancia Neta");
                      getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 110, -1));

                      jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel38.setText("GOT");
                      getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 60, -1));

                      jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel39.setText("GOT");
                      getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 60, -1));

                      jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel40.setText("Capitulos");
                      getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 110, -1));

                      jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel41.setText("Temporadas");
                      getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 110, -1));

                      jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel42.setText("Dias de duracion");
                      getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 110, -1));

                      jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel43.setText("GOT");
                      getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 60, -1));

                      jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel44.setText("GOT");
                      getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 60, -1));

                      jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel45.setText("GOT");
                      getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 60, -1));

                      jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel46.setText("Produccion:");
                      getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 110, -1));

                      jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel47.setText("Project Manager:");
                      getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 140, -1));

                      jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel48.setText("Ensambladores");
                      getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 110, -1));

                      jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel49.setText("GOT");
                      getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 60, -1));

                      jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel50.setText("Intro");
                      getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 110, -1));

                      jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel51.setText("Inicio");
                      getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, -1));

                      jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel52.setText("Cierre");
                      getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, -1));

                      jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel53.setText("Plot Twist");
                      getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 110, -1));

                      jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel54.setText("GOT");
                      getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 60, -1));

                      jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel55.setText("GOT");
                      getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 60, -1));

                      jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel56.setText("GOT");
                      getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 60, -1));

                      jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel57.setText("GOT");
                      getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 60, -1));

                      jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel58.setText("Productores:");
                      getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 120, -1));

                      jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel59.setText("Ensambladores");
                      getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 110, -1));

                      jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel60.setText("GOT");
                      getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 60, -1));

                      jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel61.setText("Intro");
                      getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, -1));

                      jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel62.setText("Inicio");
                      getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 110, -1));

                      jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel63.setText("Cierre");
                      getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 110, -1));

                      jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel64.setText("Plot Twist");
                      getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 110, -1));

                      jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel65.setText("GOT");
                      getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 60, -1));

                      jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel66.setText("GOT");
                      getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 60, -1));

                      jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel67.setText("GOT");
                      getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 60, -1));

                      jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel68.setText("GOT");
                      getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 60, -1));

                      jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel69.setText("Memoria Disponible:");
                      getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 150, -1));

                      jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel70.setText("Salario");
                      getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 110, -1));

                      jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel71.setText("Faltas");
                      getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 110, -1));

                      jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel72.setText("GOT");
                      getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 60, -1));

                      jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel73.setText("GOT");
                      getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 60, -1));

                      jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel74.setText("Facturacion:");
                      getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 110, -1));

                      jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel75.setText("Gastos");
                      getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 110, -1));

                      jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel76.setText("Ganancia Neta");
                      getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 110, -1));

                      jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel77.setText("GOT");
                      getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 60, -1));

                      jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel78.setText("GOT");
                      getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 60, -1));

                      jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel79.setText("Capitulos");
                      getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 110, -1));

                      jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel80.setText("Temporadas");
                      getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 110, -1));

                      jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                      jLabel81.setText("Dias de duracion");
                      getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 110, -1));

                      jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel82.setText("GOT");
                      getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 60, -1));

                      jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel83.setText("GOT");
                      getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 60, -1));

                      jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel84.setText("GOT");
                      getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 60, -1));

                      jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel85.setText("Produccion:");
                      getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 110, -1));

                      pack();
           }// </editor-fold>//GEN-END:initComponents

           /**
            * @param args the command line arguments
            */
           public static void main(String args[]) {
                      /* Set the Nimbus look and feel */
                      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                       */
                      try {
                                 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                            if ("Nimbus".equals(info.getName())) {
                                                       javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                       break;
                                            }
                                 }
                      } catch (ClassNotFoundException ex) {
                                 java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (InstantiationException ex) {
                                 java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (IllegalAccessException ex) {
                                 java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                                 java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      }
                      //</editor-fold>

                      /* Create and display the form */
                      java.awt.EventQueue.invokeLater(new Runnable() {
                                 public void run() {
                                            new Reporte().setVisible(true);
                                 }
                      });
           }

           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel12;
           private javax.swing.JLabel jLabel13;
           private javax.swing.JLabel jLabel14;
           private javax.swing.JLabel jLabel15;
           private javax.swing.JLabel jLabel16;
           private javax.swing.JLabel jLabel17;
           private javax.swing.JLabel jLabel18;
           private javax.swing.JLabel jLabel19;
           private javax.swing.JLabel jLabel20;
           private javax.swing.JLabel jLabel21;
           private javax.swing.JLabel jLabel22;
           private javax.swing.JLabel jLabel23;
           private javax.swing.JLabel jLabel24;
           private javax.swing.JLabel jLabel25;
           private javax.swing.JLabel jLabel26;
           private javax.swing.JLabel jLabel27;
           private javax.swing.JLabel jLabel28;
           private javax.swing.JLabel jLabel29;
           private javax.swing.JLabel jLabel3;
           private javax.swing.JLabel jLabel30;
           private javax.swing.JLabel jLabel31;
           private javax.swing.JLabel jLabel32;
           private javax.swing.JLabel jLabel33;
           private javax.swing.JLabel jLabel34;
           private javax.swing.JLabel jLabel35;
           private javax.swing.JLabel jLabel36;
           private javax.swing.JLabel jLabel37;
           private javax.swing.JLabel jLabel38;
           private javax.swing.JLabel jLabel39;
           private javax.swing.JLabel jLabel4;
           private javax.swing.JLabel jLabel40;
           private javax.swing.JLabel jLabel41;
           private javax.swing.JLabel jLabel42;
           private javax.swing.JLabel jLabel43;
           private javax.swing.JLabel jLabel44;
           private javax.swing.JLabel jLabel45;
           private javax.swing.JLabel jLabel46;
           private javax.swing.JLabel jLabel47;
           private javax.swing.JLabel jLabel48;
           private javax.swing.JLabel jLabel49;
           private javax.swing.JLabel jLabel5;
           private javax.swing.JLabel jLabel50;
           private javax.swing.JLabel jLabel51;
           private javax.swing.JLabel jLabel52;
           private javax.swing.JLabel jLabel53;
           private javax.swing.JLabel jLabel54;
           private javax.swing.JLabel jLabel55;
           private javax.swing.JLabel jLabel56;
           private javax.swing.JLabel jLabel57;
           private javax.swing.JLabel jLabel58;
           private javax.swing.JLabel jLabel59;
           private javax.swing.JLabel jLabel6;
           private javax.swing.JLabel jLabel60;
           private javax.swing.JLabel jLabel61;
           private javax.swing.JLabel jLabel62;
           private javax.swing.JLabel jLabel63;
           private javax.swing.JLabel jLabel64;
           private javax.swing.JLabel jLabel65;
           private javax.swing.JLabel jLabel66;
           private javax.swing.JLabel jLabel67;
           private javax.swing.JLabel jLabel68;
           private javax.swing.JLabel jLabel69;
           private javax.swing.JLabel jLabel7;
           private javax.swing.JLabel jLabel70;
           private javax.swing.JLabel jLabel71;
           private javax.swing.JLabel jLabel72;
           private javax.swing.JLabel jLabel73;
           private javax.swing.JLabel jLabel74;
           private javax.swing.JLabel jLabel75;
           private javax.swing.JLabel jLabel76;
           private javax.swing.JLabel jLabel77;
           private javax.swing.JLabel jLabel78;
           private javax.swing.JLabel jLabel79;
           private javax.swing.JLabel jLabel80;
           private javax.swing.JLabel jLabel81;
           private javax.swing.JLabel jLabel82;
           private javax.swing.JLabel jLabel83;
           private javax.swing.JLabel jLabel84;
           private javax.swing.JLabel jLabel85;
           private javax.swing.JPanel jPanel1;
           // End of variables declaration//GEN-END:variables
}
